### ISSUE TITLE
Cannot start application because of PersistenceManager injection

### ISSUE THREAD

**Issue by jdelibas** [liberation-data/drivine-inspiration#5] opened 2020-10-10 15:26 UTC
Local neo4j instance running at v4.1
```
docker run \     
    --publish=7474:7474 --publish=7687:7687 \
    --volume=$HOME/neo4j/data:/data \
    neo4j
```
`.env` confirguration 
```
SERVER_PORT=3000

NODE_ENV=dev

#Valid options are [VERBOSE, DEBUG, INFO, WARN, ERROR, NONE]
DRIVINE_LOG_LEVEL=VERBOSE

NEO_DATABASE_TYPE=NEO4J
NEO_DATABASE_USER=neo4j
NEO_DATABASE_PASSWORD=neo4j
NEO_DATABASE_HOST=localhost
NEO_DATABASE_PORT=7687
```

### Logs
```
[nodemon] starting `ts-node -r tsconfig-paths/register src/main.ts`
[Nest] 37857   - 10/10/2020, 17:17:39   [NestFactory] Starting Nest application...
[Nest] 37857   - 10/10/2020, 17:17:39   [InstanceLoader] AppModule dependencies initialized +18ms
[Nest] 37857   - 10/10/2020, 17:17:39   [ExceptionHandler] Nest can't resolve dependencies of the HealthRepository (?). Please make sure that the argument PersistenceManager:default at index [0] is available in the HealthModule context.

Potential solutions:
- If PersistenceManager:default is a provider, is it part of the current HealthModule?
- If PersistenceManager:default is exported from a separate @Module, is that module imported within HealthModule?
  @Module({
    imports: [ /* the Module containing PersistenceManager:default */ ]
  })
 +3ms
Error: Nest can't resolve dependencies of the HealthRepository (?). Please make sure that the argument PersistenceManager:default at index [0] is available in the HealthModule context.

Potential solutions:
- If PersistenceManager:default is a provider, is it part of the current HealthModule?
- If PersistenceManager:default is exported from a separate @Module, is that module imported within HealthModule?
  @Module({
    imports: [ /* the Module containing PersistenceManager:default */ ]
  })
```

New to nest not entirely sure where the issue is, `PersistenceManager` isnt injected into the `Health` module directly.
Two injection points I think are the `HealthRepository` and the root instantiation of `Drivine`

Is there a need to inject `PersistenceManager` into each module? 

### Note
Removed the `^` from all the deps in the package.json and deleted to package-lock.json and did a clean `npm i` still ran into the same issue.
Wanted to make sure some other dependencies weren't causing the issue

**Comment by jdelibas** [comment] 2020-10-10 15:57
Potentially related to this issue https://github.com/liberation-data/drivine/issues/47

**Comment by ElePhontitis** [comment] 2020-10-27 20:01
Experiencing the sampe problem.
app.module.ts
```@Module({
  imports: [
    DrivineModule.withOptions(<DrivineModuleOptions>{
      connectionProviders: [DatabaseRegistry.buildOrResolveFromEnv('NEO')],
    }),
    IngredientModule,
  ],
  controllers: [AppController],
  providers: [AppService],
})
export class AppModule {}
```
ingredient.module.ts

```
import { Module } from '@nestjs/common';
import { IngredientService } from './ingredient.service';
import { IngredientRepository } from './ingredient.repository';

@Module({
  providers: [IngredientService, IngredientRepository],
  exports: [IngredientService],
})
export class IngredientModule {}
```

ingredient.repository.ts

```
import { Injectable } from '@nestjs/common';
import {
  InjectPersistenceManager,
  PersistenceManager,
  QuerySpecification,
} from '@liberation-data/drivine';
import { CreateIngredientDto, Ingredient } from './model/ingredient';

@Injectable()
export class IngredientRepository {
  constructor(
    @InjectPersistenceManager() readonly persistenceManager: PersistenceManager,
  ) {}

  public async create(dto: CreateIngredientDto): Promise<Ingredient> {
    return this.persistenceManager.getOne<Ingredient>(
      new QuerySpecification<Ingredient>(
        'CREATE (i:INGREDIENT {id:apoc.create.uuid(), name: $name}) RETURN i',
      )
        .bind([dto.name])
        .transform(Ingredient),
    );
  }
}



```

**Comment by jasperblues** [comment] 2020-10-27 22:45
Remove `NEO_` prefix form the DB registration, so that it looks like: 

```
DATABASE_TYPE=NEO4J
DATABASE_USER=neo4j
DATABASE_PASSWORD=neo4j
DATABASE_HOST=localhost
DATABASE_PORT=7687
```

This is required to make `@InjectPersistenceManager(undefined/null)` to work. With the .env as is, it would be necessary to have `@InjectPersistenceManager('NEO')`

**Comment by jasperblues** [comment] 2020-10-28 11:47
All ok @ElePhontitis ? Can I close the issue?

**Comment by ElePhontitis** [comment] 2020-10-28 16:56
@jasperblues as I did not open it, I didn't feel entitled to determine that, but you have an ok from my side. Thanks a lot for your quick response!

**Comment by jasperblues** [comment] 2020-10-28 23:26
Oops, sorry! I didn't realize that there were two people having the same issue. 

Let's wait for @jdelibas to confirm that the issue is solved for him too. I'm going to have to improve the docs.

**Comment by 4lessandrodev** [comment] 2021-03-28 14:14
I Have the same problem 

my .env file
NEO_DATABASE_TYPE=NEO4J
NEO_DATABASE_USER=neo4j
NEO_DATABASE_PASSWORD=h4ckM3
NEO_DATABASE_HOST=localhost
NEO_DATABASE_PORT=7687

---

``` javascript
@Module({
  imports: [
    DrivineModule.withOptions(<DrivineModuleOptions>{
      connectionProviders: [DatabaseRegistry.buildOrResolveFromEnv('NEO')],
    }),
    UserModule,
    TaskModule,
  ],
  controllers: [AppController],
  providers: [AppService],
})
export class AppModule {}
``` 

---

``` javascript
@Injectable()
export class UserRepository {
  constructor(
    @InjectPersistenceManager('NEO')
    readonly persistenceManager: PersistenceManager,
  ) {}
```

---
Error: Nest can't resolve dependencies of the UserController (?). Please make sure that the argument UserService at index [0] is available in the UserModule context.

Potential solutions:
- If UserService is a provider, is it part of the current UserModule?
- If UserService is exported from a separate @Module, is that module imported within UserModule?
  @Module({
    imports: [ /* the Module containing UserService */ ]
  })

**Comment by 4lessandrodev** [comment] 2021-03-28 18:40
I had the same problem, but I followed the steps informed and everything went well

env file 

NEO_DATABASE_TYPE=NEO4J
NEO_DATABASE_USER=neo4j
NEO_DATABASE_PASSWORD=secure_password
NEO_DATABASE_HOST=localhost
NEO_DATABASE_PORT=7687

---

Main module

```javascript 
@Module({
  imports: [
    DrivineModule.withOptions(<DrivineModuleOptions>{
      connectionProviders: [DatabaseRegistry.buildOrResolveFromEnv('NEO')],
    }),
    UserModule,
    TaskModule,
  ],
  controllers: [AppController],
  providers: [AppService],
})
export class AppModule {}
```
---

User module context

```javascript 
@Module({
  imports: [],
  controllers: [UserController],
  providers: [UserRepository, UserService],
  exports: [],
})
export class UserModule {}
```

---

Repository 

```javascript
@Injectable()
export class UserRepository {
  constructor(
    @InjectPersistenceManager('NEO')
    readonly persistenceManager: PersistenceManager,
  ) {}

  async save(user: User): Promise<void> {
    await this.persistenceManager.execute(
      new QuerySpecification(
        `MERGE (u:User {ID: "${user.ID}", name: "${user.name}"} )`,
      ),
    );
  }
}
```

All running perfectly. I Think can close this issue 
Full example follow [Github repository](https://github.com/4lessandrodev/projeto-com-grafos)

**Closed** 2022-01-13 23:42 UTC
Labels: question
